import { LoginButton } from '@/components/auth/login-button'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import { APP_NAME } from '@/constants/strings'
import { getAuthSession } from '@/lib/next-auth'
import { redirect } from 'next/navigation'
import React from 'react'

const Home = async () => {
  const session = await getAuthSession()
  if (!session?.user)
    return (
      <section className='fixed left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2'>
        <Card className='max-w-md'>
          <CardHeader>
            <CardTitle>Welcome to {APP_NAME}</CardTitle>
            <CardDescription>
              Practice your knowlege on different topics using questions
              generated by OpenAI ChatGPT. Login today to get started.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <LoginButton />
          </CardContent>
        </Card>
      </section>
    )
  return redirect('/dashboard')
}

export default Home
